variable "vn_id" {}
variable "vn_name" {}
variable "vn_location" {}
variable "db_subnet_cidr_block" {}
variable "rg_name" {}
variable "psql_admin" {}
variable "psql_password" {}
variable "application_private_ip" {}
variable "application_name" {}
variable "db_name" {}
variable "my_ip" {}
variable "linux_admin" {}
variable "ssh_pub_key_absolute_path" {}
variable "op_mode" {}
variable "monitoring_ip" {}