- name: Retrieve DB CA Certs
  hosts: localhost
  connection: local
  vars_files:
    - db_vars.yaml
  tasks:
    - name: Get Microsoft Root CA
      ansible.builtin.get_url:
        dest: artifactory/misc/microsoft.crt
        url: 'https://www.microsoft.com/pkiops/certs/Microsoft%20RSA%20Root%20Certificate%20Authority%202017.crt'
        decompress: false
      become: yes

    - name: Get DigiCert Root CA
      ansible.builtin.get_url:
        dest: artifactory/misc/digicert.crt.pem
        url: 'https://cacerts.digicert.com/DigiCertGlobalRootG2.crt.pem'
        decompress: false
      become: yes
    
    - name: Convert Microsoft crt 
      ansible.builtin.command:
        chdir: artifactory/misc
        cmd: openssl x509 -inform DER -in microsoft.crt -out microsoft.pem -outform PEM
      become: yes
    
    - name: Create combined.pem
      ansible.builtin.command:
        cmd: touch artifactory/misc/combined.pem
      become: yes

    - name: Combine pem 
      ansible.builtin.shell:
        chdir: artifactory/misc
        cmd: cat digicert.crt.pem > combined.pem && cat microsoft.pem >> combined.pem
      become: yes
