variable "application_subnet_cidr_block" {}
variable "vn_name" {}
variable "vn_location" {}
variable "application_name" {}
variable "rg_name" {}
variable "my_ip" {}
variable "linux_admin" {}
variable "application_ip" {}
variable "psql_admin" {}
variable "psql_password" {}
variable "db_name" {}